apiVersion: v1
kind: Service
metadata:
  name: lemon-frontend-lb
  namespace: lemontech
  labels:
    app: lemon-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: lemon-frontend
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemon-frontend
  namespace: lemontech
  labels:
    app: lemon-frontend
spec:
  replicas: 1
  strategy:
  selector:
    matchLabels:
      app: lemon-frontend
  template:
    metadata:
      labels:
        app: lemon-frontend
    spec:
      containers:
        - name: lemon-frontend
          image: CONTAINER_IMAGE
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m    
            
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lemon-front-hpa
  namespace: lemontech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lemon-frontend
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50             