---
kind: pipeline
name: frontend

steps:
- name: publish  
  image: plugins/docker
  settings:
   repo: synopscl/test-lem-front
   username:
      from_secret: docker_username
   password:
      from_secret: docker_password
   dockerfile: Dockerfile
   tags: ${DRONE_BUILD_NUMBER}