---
kind: pipeline
type: docker
name: frontend

steps:


- name: install
  image: synopscl/lemon-aws-deploy:1.1
  environment:
     IMAGE: "test-lem-front"
     PROYECTO: "lemon-front"
     TAG: ${DRONE_BUILD_NUMBER}
     AWS_ACCESS_KEY_ID:
       from_secret: AWS_ACCESS_KEY_ID
     AWS_SECRET_ACCESS_KEY:
       from_secret: AWS_SECRET_ACCESS_KEY
  commands:
     - "/lemontech/run-update.sh"